### ISSUE TITLE
Implement creation of new nodes and their connections

### ISSUE THREAD

**Issue by PanekOndrej** [ansys/pyoptislang#142]
### 📝 Description of the feature

Implement functionality for creating new nodes, adding node connections and changing properties of nodes.

### 💡 Steps for implementing the feature

- server commands/queries:
  - `create_node`
     - used in `System` and child classes 
     - `System.create_node(type_: Union[NodeType, str], name: Union[str, None] = None, design_flow: Union[str, None] = None, algorithm_type: Union[str, None] = None, integration_type: Union[str, None] = None, mop_node_type: Union[str, None] = None, node_type: Union[str, None] = None)`
     - if `NodeType` is used, `algorithm_type`, `integration_type`, or ... are ignored and auto filled
     - string input can still be used, but subtype has to be specified manually if needed  
  - `remove_node`
     - used in `Node` and child classes as `Node.delete()` 
  - `connect_nodes`
     - not working for inner slots, python in optiSLang used for those
     - used in `Slot` classes (`InputSlot.connect_from`, `OutputSlot.connect_to`, ...)
  - `disconnect_slot`
     - not working for inner slots, implemented only for `InputSlot` and `OutputSlot`
  - `set_actor_property`
     - implemented in `Node` and child classes
  - `get_available_nodes`
- new classes and enumerations:
  -   `NodeType`
      - case sensitive
      - sorted by subtype, 0-999 built-in node, 1000-1999 integration plugins...
  -  `SlotType`
  -  `Slot`
     -  child classes `InputSlot`, `OutputSlot`, `InnerInputSlot`, `InnerOutputSlot`
  -  `Edge`

TODO:

- [ ] test new functionality
- [ ] document new functionality

**Comment by optislangdeveloper** [comment]
Hi, I have another request to the `create_nodes` function in `server_commands`. The function doesn't have `integration_type` and `algorithm_type` arguments. The solution I have now to create python based integration plugins is:

`        cmd=server_commands.create_node('demo_01', 'Demo', sensitivity_uid, 'RECEIVE_SEND')

        cmd_obj=json.loads(cmd)
        cmd_obj['projects'][0]['commands'][0]['args']['integration_type']='integration'

        result=osl_server.send_command(json.dumps(cmd_obj))
`
