### ISSUE TITLE
output_file argument provokes error in Optislang object constructor

### ISSUE THREAD

**Issue by optislangdeveloper** [ansys/pyoptislang#144]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

```
osl=Optislang(output_file=r'd:\tmp\logilfe.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ansysdev\pyoptislang\src\ansys\optislang\core\optislang.py", line 229, in __init__
    self.__osl_server: OslServer = self.__init_osl_server("tcp")
  File "D:\ansysdev\pyoptislang\src\ansys\optislang\core\optislang.py", line 255, in __init_osl_server
    return TcpOslServer(
  File "D:\ansysdev\pyoptislang\src\ansys\optislang\core\tcp_osl_server.py", line 1035, in __init__
    self._start_local(ini_timeout, shutdown_on_finished)
  File "D:\ansysdev\pyoptislang\src\ansys\optislang\core\tcp_osl_server.py", line 2343, in _start_local
    raise RuntimeError("Cannot get optiSLang server port.")
RuntimeError: Cannot get optiSLang server port.
```

### 📝 Steps to reproduce

Try to create an Optislang object with the output_file argument.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23 R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
-e git+https://github.com/pyansys/pyoptislang.git@936b6b8a08d6e4da053412b9fdab7e8ea54853c9#egg=ansys_optislang_core
importlib-metadata==6.7.0
psutil==5.9.5
zipp==3.15.0
```

**Comment by rfahlberg** [comment]
@optislangdeveloper  Will close this as duplicated (https://github.com/ansys/pyoptislang/issues/147). Do you agree?

**Comment by optislangdeveloper** [comment]
Yes 👍

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Ronny Fahlberg ***@***.***>
Gesendet: Thursday, June 22, 2023 1:30:18 PM
An: ansys/pyoptislang ***@***.***>
Cc: Jakob Schneider ***@***.***>; Mention ***@***.***>
Betreff: Re: [ansys/pyoptislang] output_file argument provokes error in Optislang object constructor (Issue #144)


[External Sender]

@optislangdeveloper<https://github.com/optislangdeveloper> Will close this as duplicated (#147<https://github.com/ansys/pyoptislang/issues/147>). Do you agree?
