### ISSUE TITLE
Check license status bevor starting oSL

### ISSUE THREAD

**Issue by ansDArnold** [ansys/pyoptislang#146]
### 📝 Description of the feature

once you try to start `Optislang()` without having license available leads to following error:

`RuntimeError: Cannot get optiSLang server port.
`

This is not really explaining why optiSLang could not be started.

**Comment by rfahlberg** [comment]
@ansDArnold Will close this as duplicated (https://github.com/ansys/pyoptislang/issues/147). Do you agree?

**Comment by ansDArnold** [comment]
agree, but should have and `TimeOutError` and a `LicenseMissingError`
