### ISSUE TITLE
Add interface / convenience functionality concerning result file handling needed by SAF

### ISSUE THREAD

**Issue by rfahlberg** [ansys/pyoptislang#155]
### 📝 Description of the feature

- [ ] To ParametricSystem wrapper class, add interface / convenience functionality to
  - Obtain path to result OMDB file (resemble functionality of OWS "/omdb" endpoints)
  - Generate and store a CSV/Json file containing result designs  
- [ ] To Node wrapper class, add functionality to
  - Obtain information about node result files:
    - Path on filesystem
    - Registered file ID and Comment
    - Status (exists or not) 
    - File size
    - Last modified
- [ ] To Project wrapper class, add functionality to
  - Obtain information about project result files:
    - Path on filesystem
    - Registered file ID and Comment
    - Status (exists or not) 
    - File size
    - Last modified 

Effort estimation: 1PW

### 🔗 Useful links and references

According tasks in SAF:
- https://github.com/Solution-Applications/solution-enablement-product-management/issues/484
- https://github.com/Solution-Applications/solution-enablement-product-management/issues/515

**Comment by rfahlberg** [comment]
@asbfall @iazehaf FYI

**Comment by rfahlberg** [comment]
@sebastian-wolff FYI

**Comment by PanekOndrej** [comment]
Hi Ronny, could you please clarify, what exactly you mean by `result files`? Do you mean `registered files` that I can obtain by `basic_project_info` query for the project? For nodes I can then use `get_actor_info` to obtain uids of registered files associated with individual nodes and filter whole list obtained by `basic_project_info`.

@rfahlberg

**Comment by rfahlberg** [comment]
@PanekOndrej Yes, exactly. The "result  files" are the centrally registered files, which are set to { "usage": "Output file" }. The global list can be obtained using "basic_project_info". If a registered file is not associated to (use by) a certain node, it should be accessible via pyosl "Project" interface. If a registered file is associated to (use by) a certain node, it should be accessible via pyosl "Node" interface. For nodes you can use get_actor_info to obtain uids of used registered files.

**Comment by rfahlberg** [comment]
@PanekOndrej looks very good to me. Please go ahead with unit tests and PR.

**Comment by rfahlberg** [comment]
@iazehaf Please confirm the additions are sufficient for SAF.
