### ISSUE TITLE
Bug located in server_commands.py

### ISSUE THREAD

**Issue by rfahlberg** [ansys/pyoptislang#156]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When 'actor_uid' is specified, the "hid" needs to be specified as well. This applies to following commands:
- start
- stop
- stop_gently
- restart
- reset

If "hid" is not specified when  'actor_uid' is specified, command generation should fail with error message.

### 📝 Steps to reproduce

-

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

n/a

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
n/a
```

**Comment by PanekOndrej** [comment]
I just noticed, that the check is missing in start command.
