### ISSUE TITLE
Push notification of finished execution is not delivered after using `open()` command.

### ISSUE THREAD

**Issue by PanekOndrej** [ansys/pyoptislang#182]
### 🐞 Description of the bug

Push notification of finished execution is not delivered after opening and starting project. This prevents the successful execution of the `start()` command, which waits for this push notification and either times out or remains hanging.

### 📝 Steps to reproduce

```
project_path = Path('<insert path to existing project>')

osl = Optislang()
osl.open(file_path=project_path, reset=True)
osl.start()
osl.save()
osl.dispose()
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24.1dev (604)

**Comment by rfahlberg** [comment]
@PanekOndrej Has been / will be fixed in oSL 24R1. Please verify with latest version.
