### ISSUE TITLE
Bug located in `save_copy()` command.

### ISSUE THREAD

**Issue by PanekOndrej** [ansys/pyoptislang#184]
### 🐞 Description of the bug

This command should only create a copy of the current project (don't open it), however:
 
- copy of the current project is opened
- when sending query about project info
  - `project_location` changed to the new one
  - `working_dir` remained unchanged

### 📝 Steps to reproduce

```
project_path = Path(r"<insert path to the current project>")
copy_path = Path(r"<insert path to the copy>")

optislang = Optislang(project_path=project_path, loglevel="warning")

wdir1 = optislang.get_working_dir()
loc1 = optislang.project.get_location()
uid1 = optislang.project.uid

optislang.save_copy(file_path=copy_path)
wdir2 = optislang.get_working_dir()
loc2 = optislang.project.get_location()
uid2 = optislang.project.uid

print(f"old uid: {uid1} | new uid: {uid2}")
print(f"old wdir: {wdir1} | new wdir: {wdir2}")
print(f"old loc: {loc1} | new loc: {loc2}")

optislang.dispose()
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24.1dev (604)

**Comment by rfahlberg** [comment]
@PanekOndrej Has been / will be fixed in oSL 24R1. Please verify with latest version.

**Comment by PanekOndrej** [comment]
> @PanekOndrej Has been / will be fixed in oSL 24R1. Please verify with latest version.

- succesfully tested with `24.1.0 (2648)`
  - `project location` remains unchanged
  - `wdir` remains unchanged
  - copy of the project is saved to the given location

- implement some warning  if `osl_version < 24.1` ?
- otherwise the issue can be closed
