### ISSUE TITLE
Additions to ParametricSystem and reference design

### ISSUE THREAD

**Issue by rfahlberg** [ansys/pyoptislang#77]
### 📝 Please extend implementation/exposure

ParametricSystem:
- add response_manager,
- add criteria_manager

Reference designs obtained from parametric systems:
- should contain responses (uninitialized/none)
- should contain criteria (uninitialized/none)

**Comment by PanekOndrej** [comment]
TODO LIST:
- [ ] use deepcopy only in __deepcopy__ method (not in __init__)
- [ ] general method for `from_str()` enumeration + automatize TypeError based on enumeration
- [ ] add another level in left navigation bar of `project_parametric` API documentation
- [ ] set value to `None` if `expression` is changed (`DependentParameter`, `Criteria`, `Response`)
- [ ] create chapter Criteria, Reponses in `User guide` `Project`
